import React from 'react';
import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
    return (
        <Html lang="en">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Noto+Serif:wght@500&family=Open+Sans:wght@400;600;700&display=swap" rel="stylesheet" />
            </Head>
            <body className='dark'>
                <div className='relative'>
                    <span className='h-full absolute -z-[1] w-full dark:bg-gradient-to-b from-darkGray to-black'></span>
                    <span className='h-full absolute -z-[1] w-full dark:bg-gradient-to-r from-darkGray to-black'></span>
                    <Main />
                    <NextScript />
                </div>
            </body>
        </Html>
    )
}